# Use the official httpd image from the Docker Hub
FROM httpd:latest
 
# Copy the contents of the repository to the Apache document root
COPY . /usr/local/apache2/htdocs/
 
# Expose port 80
EXPOSE 80
 
# Start the Apache server
CMD ["httpd-foreground"]
